import pandas as pd
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

FILE = BASE_DIR / "dataset" / "processed" / "sales_product_master_imputed.csv"

print("Reading dataset...")
df = pd.read_csv(FILE)

# Revenue
df["revenue"] = df["procured_quantity"] * df["unit_selling_price"]

print("\n========== PRODUCT LEVEL ANALYSIS ==========")

product = (
    df.groupby(["product_id", "product_name"], dropna=False)
      .agg(
          quantity=("procured_quantity", "sum"),
          revenue=("revenue", "sum"),
          sales_rows=("product_id", "size"),
          avg_selling_price=("unit_selling_price", "mean")
      )
      .reset_index()
)

# Sort by revenue
product = product.sort_values("revenue", ascending=False).reset_index(drop=True)

# Revenue percentage and cumulative percentage
total_revenue = product["revenue"].sum()

product["revenue_share_%"] = (
    product["revenue"] / total_revenue * 100
)

product["cumulative_revenue_%"] = (
    product["revenue_share_%"].cumsum()
)

# ABC classification
def abc_class(cumulative):
    if cumulative <= 80:
        return "A"
    elif cumulative <= 95:
        return "B"
    else:
        return "C"

product["ABC_class"] = product["cumulative_revenue_%"].apply(abc_class)


# ------------------------------------------------
# TOP 20 PRODUCTS
# ------------------------------------------------

print("\n========== TOP 20 PRODUCTS BY REVENUE ==========")

print(
    product[
        [
            "product_id",
            "product_name",
            "quantity",
            "revenue",
            "revenue_share_%",
            "cumulative_revenue_%",
            "ABC_class"
        ]
    ].head(20).to_string(index=False)
)


# ------------------------------------------------
# ABC SUMMARY
# ------------------------------------------------

print("\n========== ABC SUMMARY ==========")

abc_summary = (
    product.groupby("ABC_class")
           .agg(
               products=("product_id", "count"),
               quantity=("quantity", "sum"),
               revenue=("revenue", "sum")
           )
)

abc_summary["revenue_share_%"] = (
    abc_summary["revenue"] / total_revenue * 100
)

abc_summary["product_share_%"] = (
    abc_summary["products"] / len(product) * 100
)

print(abc_summary)


# ------------------------------------------------
# TOP 10% PRODUCTS
# ------------------------------------------------

print("\n========== TOP 10% PRODUCTS ==========")

top_10_count = max(1, int(len(product) * 0.10))

top_10_revenue = product.head(top_10_count)["revenue"].sum()

print("Total products:", len(product))
print("Top 10% product count:", top_10_count)

print(
    "Revenue generated by top 10% products:",
    top_10_revenue
)

print(
    "Top 10% revenue share:",
    round(top_10_revenue / total_revenue * 100, 2),
    "%"
)


# ------------------------------------------------
# TOP PRODUCTS BY QUANTITY
# ------------------------------------------------

print("\n========== TOP 10 PRODUCTS BY QUANTITY ==========")

top_quantity = (
    product.sort_values("quantity", ascending=False)
           .head(10)
)

print(
    top_quantity[
        [
            "product_id",
            "product_name",
            "quantity",
            "revenue",
            "ABC_class"
        ]
    ].to_string(index=False)
)


# ------------------------------------------------
# LOW REVENUE PRODUCTS
# ------------------------------------------------

print("\n========== LOWEST 10 PRODUCTS BY REVENUE ==========")

low_revenue = (
    product.sort_values("revenue", ascending=True)
           .head(10)
)

print(
    low_revenue[
        [
            "product_id",
            "product_name",
            "quantity",
            "revenue",
            "ABC_class"
        ]
    ].to_string(index=False)
)


# ------------------------------------------------
# ABC CLASS DETAILS
# ------------------------------------------------

print("\n========== ABC CLASS DETAILS ==========")

for cls in ["A", "B", "C"]:
    subset = product[product["ABC_class"] == cls]

    print(f"\nClass {cls}:")
    print("Products:", len(subset))
    print("Revenue:", subset["revenue"].sum())
    print(
        "Revenue share:",
        round(subset["revenue"].sum() / total_revenue * 100, 2),
        "%"
    )


print("\n========== DONE ==========")